import type { Evidence } from './data';

/**
 * 人工复核的义项级材料。
 *
 * 这里只收录无法由辞书释义或 CCL 自动检索可靠命中的例子；每条材料都
 * 只证明对应语境中确有此用法，不把页面日期写成词义的首次出现时间。
 */
export const manualSenseEvidence: Readonly<Record<string, Evidence>> = {
  'social-identities-02-turn': {
    id: 'official-women-equal-education-2017',
    excerpt: '“采取了一系列措施，确保女性平等的受教育权利。”',
    context: '“女性”在这里不是单纯的生理分类，而是平等教育权利所指向的社会群体与制度主体。',
    source: '教育部《关于政协十二届全国委员会第五次会议第0408号提案答复的函》',
    year: 2017,
    dateLabel: '2017-09-21（页面发布于 2018）',
    medium: '教育政策答复',
    grade: 'A',
    status: '语料事实',
    note: '可证明“女性”在教育权利语境中的群体身份用法，不用于推定这一用法的首次出现年代。',
    sourceUrl: 'https://www.moe.gov.cn/jyb_xxgk/xxgk_jyta/jyta_ghs/201801/t20180116_324806.html',
    reviewed: '已核验',
  },
  'social-identities-06-contemporary': {
    id: 'official-youthfulness-definition-2021',
    excerpt: '“少年感是一个微妙的词，是指青春活力的样子。”',
    context: '“少年感”把年龄称谓转为可感知的气质标签，并明确说明这种特征不必等同于实际年龄。',
    source: '中国大学生在线《少年感是永远保持青春活力》',
    year: 2021,
    dateLabel: '2021-08-24',
    medium: '校园文化文章',
    grade: 'A',
    status: '语料事实',
    note: '可证明“少年感”作为气质与活力评价词的公开用法，不用于判定该复合词最早出现于何时。',
    sourceUrl: 'https://dxs.moe.gov.cn/zx/a/xyh_xyh_qdnydx/210824/1723831.shtml',
    reviewed: '已核验',
  },
  'social-identities-18-turn': {
    id: 'academic-philosophy-subject-object-2001',
    excerpt: '“主体和客体构成认识活动必不可少的两极。”',
    context: '“主体”与“客体”对举，命名认识活动中能动认识的一方，体现了该词在现代哲学概念系统中的专门含义。',
    source: '《四川大学学报（哲学社会科学版）》哲学主体性研究论文摘要',
    year: 2001,
    dateLabel: '2001',
    medium: '大学学术期刊',
    grade: 'A',
    status: '语料事实',
    note: '可证明“主体”在哲学认识论中的概念用法；论文年份不是该词义的历史起点。',
    sourceUrl: 'https://journal.scu.edu.cn/info/1109/13445.htm',
    reviewed: '已核验',
  },
  'public-life-04-turn': {
    id: 'moe-dictionary-modern-party',
    excerpt: '“党”条：志同道合的人所组成的有组织、有主义的团体。',
    context: '官方辞书把现代“党”界定为有组织、有共同主张的团体，用来区分古典的同类、同辈义。',
    source: '教育部《重编国语辞典修订本》·“党”条',
    year: 2026,
    dateLabel: '网络第六版 · 2026-06-25',
    medium: '历史语言辞典',
    grade: 'A',
    status: '人文解释',
    note: '官方授权辞书义项可用于核对现代词义边界，不代表这一义项首次出现于辞书版本年份。',
    sourceUrl: 'https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/dict_reviseddict_download.html',
    reviewed: '已核验',
  },
  'public-life-12-turn': {
    id: 'moe-dictionary-modern-constitution',
    excerpt: '“宪法”条：在一国之内，规定国家体制、政府组织、人民权利义务之最高位阶法规。',
    context: '该义项明确把现代“宪法”放在国家法律体系的最高位阶，与古典“法度”义分开。',
    source: '教育部《重编国语辞典修订本》·“宪法”条',
    year: 2026,
    dateLabel: '网络第六版 · 2026-06-25',
    medium: '历史语言辞典',
    grade: 'A',
    status: '人文解释',
    note: '辞书定义用于确认现代根本法义，不用辞书发布日期推断这一概念的形成时间。',
    sourceUrl: 'https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/dict_reviseddict_download.html',
    reviewed: '已核验',
  },
  'self-and-feeling-07-turn': {
    id: 'npc-love-marriage-choice-2002',
    excerpt: '“婚姻应以互爱为前提……爱情只能产生于当事人自身。”',
    context: '人大法律释义把爱情、本人自愿与婚姻选择连在一起，明确呈现现代爱情作为个人婚姻决定基础的制度语境。',
    source: '中国人大网《婚姻法释义·第二章 结婚》',
    year: 2002,
    dateLabel: '2002-07-11',
    medium: '法律释义',
    grade: 'A',
    status: '语料事实',
    note: '该材料可证明爱情与自主婚姻在法律释义中的明确联结，不用于判定这种观念的最早形成时间。',
    sourceUrl: 'https://www.npc.gov.cn/zgrdw/npc/flsyywd/minshang/2002-07/11/content_297450.htm',
    reviewed: '已核验',
  },
  'self-and-feeling-11-contemporary': {
    id: 'xjtu-digital-intimacy-lecture-2024',
    excerpt: '“探讨数字亲密的概念……以及如何通过数字技术重新定义我们关于亲密和连接的理解。”',
    context: '“数字亲密”把亲密关系置于人与数字技术的互动之中，显示亲密已成为可由媒介条件重塑的关系概念。',
    source: '西安交通大学学术资源平台《真正的亲密关系可能通过科技实现吗？》',
    year: 2024,
    dateLabel: '2024',
    medium: '大学学术讲座',
    grade: 'A',
    status: '语料事实',
    note: '可证明“数字亲密”在当代学术讨论中的明确使用，不代表该概念始于讲座年份。',
    sourceUrl: 'https://meeting.xjtu.edu.cn/lecturenotice/6320.htm',
    reviewed: '已核验',
  },
  'platform-culture-03-prehistory': {
    id: 'official-like-compound-boundary-2020',
    excerpt: '“共吸引网民观看1970万人次，点赞416万人次。”',
    context: '“点赞”已作为一个完整动词与次数统计搭配；该节点只标示“点按＋称赞”复合词形已经稳定，不虚构更早的独立旧义。',
    source: '中国网信网《镜头中的脱贫故事网络直播安徽站活动》',
    year: 2020,
    dateLabel: '2020-11-05',
    medium: '网络新闻',
    grade: 'A',
    status: '语料事实',
    note: '官方页面可证明复合词形的实际使用；这里不以 2020 年作为“点赞”的首见年份。',
    sourceUrl: 'https://www.cac.gov.cn/2020-11/05/c_1606140422457799.htm',
    reviewed: '已核验',
  },
  'platform-culture-07-prehistory': {
    id: 'official-hot-search-compound-boundary-2020',
    excerpt: '“一度占据微博热搜榜首。”',
    context: '“热搜”与“榜首”组合，显示“热门搜索”已经缩合为平台榜单名词；该节点用于说明词形边界，而不是设置一个虚构古义。',
    source: '中国网信网《镜头中的脱贫故事网络直播安徽站活动》',
    year: 2020,
    dateLabel: '2020-11-05',
    medium: '网络新闻',
    grade: 'A',
    status: '语料事实',
    note: '官方页面可证明“热搜”缩合词的实际使用；不据此推断首次出现时间。',
    sourceUrl: 'https://www.cac.gov.cn/2020-11/05/c_1606140422457799.htm',
    reviewed: '已核验',
  },
};
