import type { Evidence } from './data';

function officialEvidence(
  word: string,
  excerpt: string,
  context: string,
  source: string,
  year: number,
  medium: string,
  sourceUrl: string,
): Evidence {
  return {
    id: `official-modern-${word}`,
    excerpt,
    context,
    source,
    year,
    medium,
    grade: 'A',
    status: '语料事实',
    note: '这条材料用于证明该词在当代公开文本中的实际用法，不用于推定首次出现年代。',
    sourceUrl,
    reviewed: '已核验',
  };
}

export const modernEvidence: Readonly<Record<string, Evidence>> = {
  网民: officialEvidence(
    '网民',
    '“广大网民对网络信息要仔细辨别、认真判断。”',
    '“网民”在这里指网络信息的发布、转发与判断者，是按互联网参与行为形成的人群称谓。',
    '镶黄旗网信办、公安局《关于依法打击网络谣言的通告》',
    2020,
    '政府通告',
    'https://www.nmxhq.gov.cn/nmxhq/zwgk/xxgk/zfxxgkml/hygq/04f8c419f689463fb3a1e2dac584715a/index.html',
  ),
  群众: officialEvidence(
    '群众',
    '“关乎人民群众生命安全，关乎社会大局稳定和谐。”',
    '“群众”在政府公开文本中指向受公共事务影响的广泛普通人群。',
    '镶黄旗网信办、公安局《关于依法打击网络谣言的通告》',
    2020,
    '政府通告',
    'https://www.nmxhq.gov.cn/nmxhq/zwgk/xxgk/zfxxgkml/hygq/04f8c419f689463fb3a1e2dac584715a/index.html',
  ),
  文本: officialEvidence(
    '文本',
    '“法律草案文本是开展制定、修改、废止法律工作的前提。”',
    '“文本”在此不只是字符串，而是承载完整法律内容与结构的标准化文件。',
    '中国人大网《立法法释义·第二章 法律》',
    2001,
    '立法释义',
    'https://www.npc.gov.cn/WZWSREL3pncmR3Ly9ucGMvLy8vLy8vZmxzeXl3ZC94aWFuZmEvMjAwMS0wOC8wMS9jb250ZW50XzE0MDQwNy5odG0%3D',
  ),
  端口: officialEvidence(
    '端口',
    '“设备终端应支持同时连接两个或两个以上的视频监控中心 IP 端口。”',
    '“端口”与 IP 地址和编号搭配，指网络通信中用于接入与区分服务的连接点。',
    '中山市城市管理和综合执法局《设备终端接入要求》',
    2023,
    '技术要求',
    'https://csglhzhzf.zs.gov.cn/attachment/0/471/471402/2296424.pdf',
  ),
  终端: officialEvidence(
    '终端',
    '“工业物联网平台 终端设备接入规范。”',
    '“终端设备”在国家标准项目中指与工业物联网平台连接的感知、控制或计算设备。',
    '全国标准信息公共服务平台《工业物联网平台 终端设备接入规范》项目',
    2019,
    '国家标准项目',
    'https://std.samr.gov.cn/gb/search/gbDetailed?id=5DDA8B9DC4AC18DEE05397BE0A0A95A7',
  ),
  点赞: officialEvidence(
    '点赞',
    '“共吸引网民观看1970万人次，点赞416万人次。”',
    '“点赞”与人次统计搭配，显示平台按钮动作已成为可计量的受众反馈指标。',
    '中国网信网《镜头中的脱贫故事网络直播安徽站活动》',
    2020,
    '网络新闻',
    'https://www.cac.gov.cn/2020-11/05/c_1606140422457799.htm',
  ),
  热搜: officialEvidence(
    '热搜',
    '“一度占据微博热搜榜首。”',
    '“热搜”与榜首搭配，指平台按搜索与讨论热度排列的实时议题榜单。',
    '中国网信网《镜头中的脱贫故事网络直播安徽站活动》',
    2020,
    '网络新闻',
    'https://www.cac.gov.cn/2020-11/05/c_1606140422457799.htm',
  ),
  社群: officialEvidence(
    '社群',
    '“网络社群，是成员分享共同经历或兴趣爱好的共同体。”',
    '“社群”在这里不只是人数集合，而是基于共同经历、兴趣与行动形成的线上共同体。',
    '湖南智库网《善用流量逻辑构建新型线上社区》',
    2022,
    '政府智库文章',
    'https://www.hnzk.gov.cn/zhikujianyan/17369.html',
  ),
  博主: officialEvidence(
    '博主',
    '“博主用个人创作的视频记录日常生活。”',
    '“博主”从博客主人扩展到以个人视频进行持续创作和公开表达的账号身份。',
    '中国网信网《Vlog流行，年轻人的网络社交悄悄改变》',
    2019,
    '网络新闻',
    'https://www.cac.gov.cn/2019-05/23/c_1124531231.htm',
  ),
  账号: officialEvidence(
    '账号',
    '“互联网用户账号名称，是机构或个人在互联网信息服务中注册或使用的账号名称。”',
    '“账号”在这里是互联网服务中可注册、认证、管理与归责的数字身份载体。',
    '国家互联网信息办公室《互联网用户账号名称管理规定》',
    2015,
    '部门规定',
    'https://www.cac.gov.cn/2015-02/04/c_1114246561.htm',
  ),
  弹幕: officialEvidence(
    '弹幕',
    '“弹幕也已成为年轻人交流中不可或缺的方式。”',
    '“弹幕”指与视频播放同步出现的滚动评论，同时也命名了一种共时观看文化。',
    '安徽网信网《弹幕玩出网络文化新图景》',
    2020,
    '网络文化报道',
    'https://www.ahwx.gov.cn/wlyj/202006/t20200615_4584673.html',
  ),
  头像: officialEvidence(
    '头像',
    '“账号名称、头像和简介等注册信息。”',
    '“头像”在互联网账号规定中与名称、简介并列，成为可审核的数字身份信息。',
    '国家互联网信息办公室《互联网用户账号名称管理规定》',
    2015,
    '部门规定',
    'https://www.cac.gov.cn/2015-02/04/c_1114246561.htm',
  ),
  朋友圈: officialEvidence(
    '朋友圈',
    '“在微信群（朋友圈）、贴吧、微博等网络平台上发布、转发不实信息。”',
    '“朋友圈”在此是微信中发布和转发内容的半私密社交场景，不再只是普通的朋友圈层。',
    '镶黄旗网信办、公安局《关于依法打击网络谣言的通告》',
    2020,
    '政府通告',
    'https://www.nmxhq.gov.cn/nmxhq/zwgk/xxgk/zfxxgkml/hygq/04f8c419f689463fb3a1e2dac584715a/index.html',
  ),
};
